name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 

      - name: Activate Virtualenv
        run: source ../venv/bin/activate 

      - name: Install Python Dependencies
        run: cd backend && pip install -r requirements.txt
        
      - name: Update code
        run: git pull

      - name: reload gunicorn
        run: sudo systemctl restart gunicorn
